# numpy.where()用法

### 1. numpy.where(condition, x, y)
即numpy.where(expr, Trur, False)；滿足條件(condition)，輸出x，不滿足輸出y。

In [1]:
import numpy as np

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.where(a<5,a,a*10) 

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [3]:
np.where([[True, False], [True, False]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]]
        )

array([[1, 8],
       [3, 6]])

上面這個例子的條件為[[True,False], [True,False]]，分別對應最後輸出結果的四個值。第一個值從[1,9]中選，因為條件為True，所以是選1。第二個值從[2,8]中選，因為條件為False，所以選8，後面以此類推。類似的問題可以再看個例子：

In [4]:
a = 10
np.where([[a > 5,a < 5], [a == 10,a == 7]],
         [[1,2], [3,4]],
         [[9,8], [7,6]])

array([[1, 8],
       [3, 6]])

另外也能擴展成矩陣

In [5]:
x, y = np.ogrid[:3, :4]
x

array([[0],
       [1],
       [2]])

In [6]:
y

array([[0, 1, 2, 3]])

In [7]:
np.where(x < y,x,10+y)

array([[10,  0,  0,  0],
       [10, 11,  1,  1],
       [10, 11, 12,  2]])

F,T,T,T   (0,0),(0,1),(0,2),(0,3)
F,F,T,T   (1,0),(1,1),(1,2),(1,3)
F,F,F,T   (2,0),(2,1),(2,2),(2,3)

### 2. np.where(condition)
參數只有條件的話，則以TUPLE形式回傳符合條件的元素座標

In [8]:
a = np.array([2,4,6,8,10])
np.where(a > 5)

(array([2, 3, 4], dtype=int64),)

In [9]:
 a[np.where(a > 5)] 

array([ 6,  8, 10])

In [10]:
 np.where([[1, 0], 
           [1, 0]])

(array([0, 1], dtype=int64), array([0, 0], dtype=int64))

上面的例子回傳的是1的位置(1 = True)
array([0,1],  行
      [0,0])  列


In [11]:
np.where([[1, 1], 
          [1, 1]])

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

array([0,0,1,1], 表示(0,0)(0,1)(1,0)(1,1)位置為True
      [0,1,0,1])

In [12]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
np.where(a > 5)

(array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       dtype=int64),
 array([2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2],
       dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       dtype=int64))

(0,2,0)(0,2,1)(0,2,2)...符合`a>5`的條件